#+TITLE: 3D Seismic Wave Propagation
This repo contains the source code for a Finite Element simulation for calculating the propagation of seismic waves, and the accompanies Nix development environment via ~flake.nix~.

* How to Compile the simulation
Included in this directory is a makefile. This make file is about as simple as possible for a PETSc document and is reproduced in its entirety below:
#+BEGIN_SRC make
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
#+END_SRC
This uses the users installation of ~PETSC_DIR~ to include some standard variables and build targets for a PETSC application. Alternatively we could specify each included library in our makefile.

To compile all we need to do is:
#+BEGIN_SRC bash
make main
#+END_SRC
Which will compile the ~main.c~ file and link the appropriate PETSc libraries

* How to run the simulation
This is a multi-processor example. In general we could run a ~PETSc~ progam as follows:
#+BEGIN_SRC bash
mpiexec -n 8 ./petsc_program_name petsc_options
#+END_SRC
Therefore, the simplest way of running the ~main.c~ file in this repository is:
#+BEGIN_SRC bash
mpiexec -n 2 ./main
#+END_SRC

In this simulation, on line 85-88 we have checked if the user has provided the value of ~dim~ , ~dt~, ~nsteps~, and ~dump_output~, where:
- ~dim~ is the dimension of the problem
- ~dt~ is the size of the time-steps
- ~nsteps~ is the number of time-steps
- ~dump_output~ is a boolean operator which specifies if the program should dump the output to stdout. 
That means we can supply this value at runtime as follows:
#+BEGIN_SRC bash
mpiexec -n 1 ./main -n 100
#+END_SRC
This will override the default value of ~n = 10~ and run the simulation with ~n = 100~ 
